(defun insert-stars ()
  (let* ((line)
         (overlay)
         (start (point))
         (stars "*⋆★☆✦✧✩✫✬✭✴✵✶✷")
         (colors '("#CCEEFF" "#FFFFFF" "#FFDCDD" "#BBFFEE" "#FFFFBB"))
         (color (nth (random (length colors)) colors))
         (pick-char (lambda ()
                      (if (= 0 (random 22))
                          (char-to-string (aref stars (random (length stars))))
                        " "))))
    (dotimes (i 80)
      (setq line (cons (eval (list pick-char)) line)))
    (insert (apply 'concat ";" line))
    (setq overlay (make-overlay (+ 1 (point-at-bol)) (point-at-eol)))
    (overlay-put overlay 'face `(:foreground ,color))
    (newline)))
