(defun insert-stars ()
  (let* ((line)
         (stars "*⋆★☆✦✧✩✫✬✭✴✵✶✷")
         (pick-char (lambda ()
                      (if (= 0 (random 22))
                          (char-to-string (aref stars (random (length stars))))
                        " "))))
    (dotimes (i 80)
      (setq line (cons (eval (list pick-char)) line)))
    (insert (apply 'concat ";" line))
    (newline)))
